#!/bin/bash

for i in `seq -w 01 30`
do

./EventGen > out/out.dat <<EOF
2
1
2
3
-1
3
1
150
450
1
2
100000
    
EOF

mv out/out.dat out/g-p_pi0-p_long_neg_cm12/EventGen_g-p_pi0-p_long_neg_cm12_${i}.dat
#mv out/hist.root ~/work0/MC/g-p_pi0-p/EventGen_g-p_pi0-p_isot_${i}.hist.root
mv out/ntpl.root out/g-p_pi0-p_long_neg_cm12/EventGen_g-p_pi0-p_long_neg_cm12_${i}.root
#mv out/tree.root ~/work0/MC/g-p_pi0-p/EventGen_g-p_pi0-p_isot_${i}.tree.root

done
