#!/bin/bash

for i in `seq -w 01 50`
do

./EventGen > out/out.dat <<EOF
2
3
1
3
270.00
350.00
200000
    
EOF

mv out/out.dat ~/work0/MC/g-C12_pi0-C12/EventGen_g-C12_pi0-C12_isot_${i}.dat
#mv out/hist.root ~/work0/MC/g-C12_pi0-C12/EventGen_g-C12_pi0-C12_isot_${i}.hist.root
mv out/ntpl.root ~/work0/MC/g-C12_pi0-C12/EventGen_g-C12_pi0-C12_isot_${i}.root
#mv out/tree.root ~/work0/MC/g-C12_pi0-C12/EventGen_g-C12_pi0-C12_isot_${i}.tree.root

done
